const PUBLIC_UPLOADS_PREFIX = '/uploads';
const PRIVATE_PREFIX = '/private';
const THUMBNAILS_PREFIX = `${PUBLIC_UPLOADS_PREFIX}/thumbnails`;
const SOCIAL_PREFIX = `${PUBLIC_UPLOADS_PREFIX}/social`;

const ASSET_PATHS = Object.freeze({
    PRIVATE_PREFIX,
    PRIVATE_SOURCE_PREFIX: `${PRIVATE_PREFIX}/source`,
    PUBLIC_UPLOADS_PREFIX,
    SOCIAL_PREFIX,
    SOCIAL_ROUTE_PREFIX: '/social/',
    THUMBNAILS_PREFIX,
    THUMBNAILS_ROUTE_PREFIX: '/thumbnails/',
    THUMBNAIL_11_PREFIX: `${THUMBNAILS_PREFIX}/1x1`,
    THUMBNAIL_43_PREFIX: `${THUMBNAILS_PREFIX}/4x3`
});

module.exports = ASSET_PATHS;
